name: Tweet PORK Stats

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
    - name: Run Twitter Bot
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
        ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
      run: node coin.js
