name: Tweet PORK Stats

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Install dependencies
      run: |
        npm install
        npm list
    - name: Debug Environment
      run: |
        node -v
        npm -v
        ls -la
        cat package.json
    - name: Run Twitter Bot
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}  # Include Bearer Token
        COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}      # Include CoinGecko API Key
        ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}          # Include Alchemy API Key
      run: node coin.js